### ISSUE TITLE
unexpected character: # (ASCII 35) (C::ParseError)

### ISSUE THREAD

**Issue by timuckun** [oggy/cast#15]
```ruby
#!/usr/bin/env ruby
require 'cast'
source = File.read('lmdb.h')
ast = C.parse(source)
ast.entities.each do |declaration|
  declaration.declarator.each do |declarator|
    puts "#{declarator.name}: declarator.type"
  end
```

Gives the error

```bash
c.y:593:in `parse': 165: unexpected character: # (ASCII 35) (C::ParseError)
        from /Users/tim/.gem/ruby/2.4.1/gems/cast-0.3.0/lib/cast/parse.rb:57:in `parse'
        from /Users/tim/.gem/ruby/2.4.1/gems/cast-0.3.0/lib/cast/parse.rb:51:in `parse'
        from ./cast.rb:4:in `<main>'
```

The line in question is.

```c
#ifndef _LMDB_H_
#define _LMDB_H_
```

**Comment by oggy** [comment]
Hi Tim, please see the "preprocessing" notes under "parsing full programs" in the readme.
